
package es.panel.cientouno.wsclient.padron;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-24T01:12:24.568+02:00
 * Generated source version: 3.0.4
 * 
 */
public final class PadronService_PadronServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/PadronService/", "PadronService");

    private PadronService_PadronServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        //URL wsdlURL = PadronService_Service.WSDL_LOCATION;
        
        URL wsdlURL = new URL("http://localhost:8088/mockPadronServiceSOAP?wsdl");
        
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
      
        PadronService_Service ss = new PadronService_Service(wsdlURL, SERVICE_NAME);
        PadronService port = ss.getPadronServiceSOAP();  
        
        {
        System.out.println("Invoking consultaPadron...");
        //es.panel.cientouno.wsclient.padron.ConsultaPadron _consultaPadron_parameters = null;
        
        ConsultaPadron consulta = new ConsultaPadron();
        consulta.setDocumento("11111111H");
        consulta.setNombre("David");
        consulta.setPrimerApellido("Garcia");
        
        es.panel.cientouno.wsclient.padron.ConsultaPadronResponse _consultaPadron__return = port.consultaPadron(consulta);
        System.out.println(_consultaPadron__return.getDomicilio().getVia());
        System.out.println("consultaPadron.result=" + _consultaPadron__return);


        }

        System.exit(0);
    }

}
