package es.panel.cientouno.wsclient.padron;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-24T01:12:26.602+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.example.org/PadronService/", name = "PadronService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PadronService {

    @WebMethod(operationName = "ConsultaPadron", action = "http://www.example.org/PadronService/ConsultaPadron")
    @WebResult(name = "ConsultaPadronResponse", targetNamespace = "http://www.example.org/PadronService/", partName = "parameters")
    public ConsultaPadronResponse consultaPadron(
        @WebParam(partName = "parameters", name = "ConsultaPadron", targetNamespace = "http://www.example.org/PadronService/")
        ConsultaPadron parameters
    );
}
