package es.panel.cientouno.wsclient.padron;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-24T01:12:27.199+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "PadronService", 
                  wsdlLocation = "PadronService.wsdl",
                  targetNamespace = "http://www.example.org/PadronService/")
@Deprecated
public class PadronService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/PadronService/", "PadronService");
    public final static QName PadronServiceSOAP = new QName("http://www.example.org/PadronService/", "PadronServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/PROYECTOS/101/workspace/cientouno/cientouno-wsclient-padron/src/main/resources/PadronService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PadronService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/PROYECTOS/101/workspace/cientouno/cientouno-wsclient-padron/src/main/resources/PadronService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PadronService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PadronService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PadronService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PadronService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PadronService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PadronService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PadronService
     */
    @WebEndpoint(name = "PadronServiceSOAP")
    public PadronService getPadronServiceSOAP() {
        return super.getPort(PadronServiceSOAP, PadronService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PadronService
     */
    @WebEndpoint(name = "PadronServiceSOAP")
    public PadronService getPadronServiceSOAP(WebServiceFeature... features) {
        return super.getPort(PadronServiceSOAP, PadronService.class, features);
    }

}
