package es.panel.cientouno.wsclient.agenciatributaria;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-24T03:28:50.717+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "AgenciaTributariaService", 
                  wsdlLocation = "AgenciaTributariaService.wsdl",
                  targetNamespace = "http://www.example.org/AgenciaTributariaService/")
@Deprecated
public class AgenciaTributariaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/AgenciaTributariaService/", "AgenciaTributariaService");
    public final static QName AgenciaTributariaServiceSOAP = new QName("http://www.example.org/AgenciaTributariaService/", "AgenciaTributariaServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/PROYECTOS/101/workspace/cientouno/cientouno-wsclient-agenciatributaria/src/main/resources/AgenciaTributariaService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AgenciaTributariaService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/PROYECTOS/101/workspace/cientouno/cientouno-wsclient-agenciatributaria/src/main/resources/AgenciaTributariaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AgenciaTributariaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AgenciaTributariaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgenciaTributariaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AgenciaTributariaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AgenciaTributariaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AgenciaTributariaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns AgenciaTributariaService
     */
    @WebEndpoint(name = "AgenciaTributariaServiceSOAP")
    public AgenciaTributariaService getAgenciaTributariaServiceSOAP() {
        return super.getPort(AgenciaTributariaServiceSOAP, AgenciaTributariaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgenciaTributariaService
     */
    @WebEndpoint(name = "AgenciaTributariaServiceSOAP")
    public AgenciaTributariaService getAgenciaTributariaServiceSOAP(WebServiceFeature... features) {
        return super.getPort(AgenciaTributariaServiceSOAP, AgenciaTributariaService.class, features);
    }

}
