
package es.panel.cientouno.wsclient.agenciatributaria;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-24T03:28:50.622+02:00
 * Generated source version: 3.0.4
 * 
 */
public final class AgenciaTributariaService_AgenciaTributariaServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/AgenciaTributariaService/", "AgenciaTributariaService");

    private AgenciaTributariaService_AgenciaTributariaServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AgenciaTributariaService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AgenciaTributariaService_Service ss = new AgenciaTributariaService_Service(wsdlURL, SERVICE_NAME);
        AgenciaTributariaService port = ss.getAgenciaTributariaServiceSOAP();  
        
        {
        System.out.println("Invoking consultaIrpf...");
        es.panel.cientouno.wsclient.agenciatributaria.ConsultaIrpf _consultaIrpf_parameters = null;
        es.panel.cientouno.wsclient.agenciatributaria.ConsultaIrpfResponse _consultaIrpf__return = port.consultaIrpf(_consultaIrpf_parameters);
        System.out.println("consultaIrpf.result=" + _consultaIrpf__return);


        }

        System.exit(0);
    }

}
