package es.panel.cientouno.wsclient.agenciatributaria;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-24T03:28:50.707+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.example.org/AgenciaTributariaService/", name = "AgenciaTributariaService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AgenciaTributariaService {

    @WebMethod(operationName = "ConsultaIrpf", action = "http://www.example.org/AgenciaTributariaService/ConsultaIrpf")
    @WebResult(name = "ConsultaIrpfResponse", targetNamespace = "http://www.example.org/AgenciaTributariaService/", partName = "parameters")
    public ConsultaIrpfResponse consultaIrpf(
        @WebParam(partName = "parameters", name = "ConsultaIrpf", targetNamespace = "http://www.example.org/AgenciaTributariaService/")
        ConsultaIrpf parameters
    );
}
