
package es.panel.cientouno.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-23T01:21:15.561+02:00
 * Generated source version: 3.0.4
 * 
 */
 
public class SolicitudCientouno_SolicitudCientounoSOAP_Server{

    protected SolicitudCientouno_SolicitudCientounoSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SolicitudCientounoSOAPImpl();
        String address = "http://panel.es/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SolicitudCientouno_SolicitudCientounoSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
