package es.panel.cientouno.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-23T01:21:15.552+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://panel.es/solicitud-cientouno/", name = "solicitud-cientouno")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SolicitudCientouno {

    @WebMethod(operationName = "Cientouno", action = "http://panel.es/solicitud-cientouno/Cientouno")
    @WebResult(name = "CientounoResponse", targetNamespace = "http://panel.es/solicitud-cientouno/", partName = "parameters")
    public CientounoResponse cientouno(
        @WebParam(partName = "parameters", name = "Cientouno", targetNamespace = "http://panel.es/solicitud-cientouno/")
        Cientouno parameters
    );
}
