package es.panel.cientouno.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-04-23T01:21:15.566+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "solicitud-cientouno", 
                  wsdlLocation = "file:/D:/PROYECTOS/101/workspace/cientouno/cientouno-solicitud-ws/src/main/resources/solicitud-cientouno.wsdl",
                  targetNamespace = "http://panel.es/solicitud-cientouno/") 
public class SolicitudCientouno_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://panel.es/solicitud-cientouno/", "solicitud-cientouno");
    public final static QName SolicitudCientounoSOAP = new QName("http://panel.es/solicitud-cientouno/", "solicitud-cientounoSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/PROYECTOS/101/workspace/cientouno/cientouno-solicitud-ws/src/main/resources/solicitud-cientouno.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SolicitudCientouno_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/PROYECTOS/101/workspace/cientouno/cientouno-solicitud-ws/src/main/resources/solicitud-cientouno.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SolicitudCientouno_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SolicitudCientouno_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolicitudCientouno_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SolicitudCientouno_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SolicitudCientouno_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SolicitudCientouno_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SolicitudCientouno
     */
    @WebEndpoint(name = "solicitud-cientounoSOAP")
    public SolicitudCientouno getSolicitudCientounoSOAP() {
        return super.getPort(SolicitudCientounoSOAP, SolicitudCientouno.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolicitudCientouno
     */
    @WebEndpoint(name = "solicitud-cientounoSOAP")
    public SolicitudCientouno getSolicitudCientounoSOAP(WebServiceFeature... features) {
        return super.getPort(SolicitudCientounoSOAP, SolicitudCientouno.class, features);
    }

}
